# Experiment 1: Pretrained `google/flan-t5-base` Baseline

Evaluates the **untuned** FLAN-T5 Base model on the fixed test split (`data/splits/test.csv`) with no fine-tuning.

This notebook reuses the repository modules:
- `src/data.py` — load split and build prompts
- `src/inference.py` — model loading and batched generation
- `src/metrics.py` — exact-match, precision, recall, F1, per-subcategory accuracy
- `scripts/run_experiment.py` — orchestration and saving results

**Runtime:** GPU recommended (~10–20 min for 1,079 test examples).

## 1. Clone repository and install dependencies

In [1]:
import os
from pathlib import Path

REPO_URL = "https://github.com/L0ki2026/FLAN-T5_Base.git"
REPO_ROOT = Path("/content/FLAN-T5_Base")

if not REPO_ROOT.exists():
    !git clone {REPO_URL} {REPO_ROOT}
else:
    %cd {REPO_ROOT}
    !git pull

%cd {REPO_ROOT}
!pip install -q -r requirements.txt

Cloning into '/content/FLAN-T5_Base'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 25 (delta 3), reused 24 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 10.22 MiB | 18.27 MiB/s, done.
Resolving deltas: 100% (3/3), done.
/content/FLAN-T5_Base

## 2. Verify GPU

In [2]:
import torch

assert torch.cuda.is_available(), "Enable Runtime > Change runtime type > GPU before running inference."
print(f"Device: {torch.cuda.get_device_name(0)}")

Device: Tesla T4

## 3. Run Experiment 1 (no training)

In [3]:
import sys

sys.path.insert(0, str(REPO_ROOT))

from scripts.run_experiment import run_experiment, print_metrics_summary

metrics = run_experiment(
    experiment_name="experiment_1_pretrained",
    model_name="google/flan-t5-base",
    split="test",
    batch_size=16,
    device="cuda",
)

print_metrics_summary(metrics)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

func-calling-singleturn.json: reconstructing file:   0%|          |  0.00B / 17.8MB

func-calling-singleturn.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1893 [00:00<?, ? examples/s]

func-calling.json: reconstructing file:   0%|          |  0.00B / 20.6MB

func-calling.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1893 [00:00<?, ? examples/s]

glaive-function-calling-5k.json: reconstructing file:   0%|          |  0.00B / 20.4MB

glaive-function-calling-5k.json: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/5209 [00:00<?, ? examples/s]

json-mode-agentic.json:   0%|          | 0.00/5.02M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1342 [00:00<?, ? examples/s]

json-mode-singleturn.json:   0%|          | 0.00/2.95M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1241 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Generating: 100%|██████████| 68/68 [28:40<00:00, 25.29s/it]

Experiment: experiment_1_pretrained
Model: google/flan-t5-base
Split: test (1079 examples)
Exact-match accuracy: 0.0000
Precision: 0.0000
Recall: 0.0000
F1: 0.0000

## 4. Inspect results

In [4]:
import json
import pandas as pd

output_dir = REPO_ROOT / "experiments" / "experiment_1_pretrained"

with open(output_dir / "metrics.json") as f:
    saved_metrics = json.load(f)

print("Overall metrics:")
display(pd.DataFrame([saved_metrics["overall"]]))

per_sub = pd.DataFrame(saved_metrics["per_subcategory"]).T
per_sub.index.name = "subcategory"
per_sub = per_sub.reset_index().sort_values("accuracy", ascending=False)

print("\nTop 10 subcategories by accuracy:")
display(per_sub.head(10))

print("\nBottom 10 subcategories by accuracy (min 5 examples):")
display(per_sub[per_sub["count"] >= 5].tail(10))

Overall metrics:

   exact_match_accuracy  precision  recall   f1  num_examples
0                   0.0        0.0     0.0  0.0          1079

Top 10 subcategories by accuracy:

                 subcategory  count  accuracy
456                   iPhone    3.0       0.0
0                JSON Schema    5.0       0.0
1         AI Code Generation    1.0       0.0
2         AI Test Generation    1.0       0.0
3                        AWS    1.0       0.0
4             Access Control    1.0       0.0
5             Action History    1.0       0.0
6           Action Selection    1.0       0.0
7         Ad Copy Generation    1.0       0.0
417  Technology Distributors    1.0       0.0

Bottom 10 subcategories by accuracy (min 5 examples):

                     subcategory  count  accuracy
265            Instructor Agents    7.0       0.0
326  Oil, Gas & Consumable Fuels    5.0       0.0
312              Metals & Mining    6.0       0.0
344                   Play Music    7.0       0.0
387                 Search Movie    7.0       0.0
389                Search Movies   16.0       0.0
392                Search Recipe    8.0       0.0
382                 Search Books    7.0       0.0
433               Translate Text    7.0       0.0
437                      Unknown   87.0       0.0

In [5]:
from scripts.run_experiment import format_readme_results

print("Copy the block below into README.md under Experiment 1 > Results:\n")
print(format_readme_results(saved_metrics))
print("\n---\n")
print("Brief findings template:")
overall = saved_metrics["overall"]
print(
    f"- Pretrained FLAN-T5 Base achieves {overall['exact_match_accuracy']:.1%} exact-match accuracy "
    f"on the Hermes function-calling test split without task-specific training."
)
print("- Structured JSON and `<tool_call>` outputs are largely missed; free-text responses dominate predictions.")
print("- This run establishes the no-training baseline for later fine-tuning experiments.")

Copy the block below into README.md under Experiment 1 > Results:

### Results (test set)

| Metric | Value |
|--------|-------|
| Exact-match accuracy | 0.0000 |
| Precision | 0.0000 |
| Recall | 0.0000 |
| F1 | 0.0000 |
| Examples | 1079 |

**Top subcategories (accuracy, n ≥ 5):**
- Unknown: 0.000 (87 examples)
- Json Schema: 0.000 (80 examples)
- Convert Currency: 0.000 (39 examples)
- Get Stock Price: 0.000 (33 examples)
- Generate Random Number: 0.000 (32 examples)

**Weakest subcategories (accuracy, n ≥ 5):**
-  JSON Schema: 0.000 (5 examples)
- Calculate Distance: 0.000 (9 examples)
- Calculate Loan Payment: 0.000 (19 examples)
- Calculate Mortgage Payment: 0.000 (12 examples)
- Calculate Tax: 0.000 (5 examples)

---

Brief findings template:
- Pretrained FLAN-T5 Base achieves 0.0% exact-match accuracy on the Hermes function-calling test split without task-specific training.
- Structured JSON and `<tool_call>` outputs are largely missed; free-text responses dominate predictions.
- This run establishes the no-training baseline for later fine-tuning experiments.

## 5. Commit and push results to GitHub

Configure a [GitHub personal access token](https://github.com/settings/tokens) with `repo` scope, then run the cell below.

In [10]:
from getpass import getpass

GITHUB_TOKEN = getpass("Paste new GitHub token: ")
GITHUB_USER = input("GitHub username: ")

!git config user.email "colab@users.noreply.github.com"
!git config user.name "Colab Experiment 1"

!git add experiments/experiment_1_pretrained/ README.md
!git status

!git commit -m "Add Experiment 1 pretrained baseline results from Colab" || echo "Nothing to commit"

remote_url = f"https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/L0ki2026/FLAN-T5_Base.git"
!git push {remote_url} main

Paste new GitHub token: ··········
GitHub username: L0ki2026
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Nothing to commit
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 894.24 KiB | 5.42 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/L0ki2026/FLAN-T5_Base.git
   8270da8..9c23bca  main -> main

In [9]:
import requests

r = requests.get(
    "https://api.github.com/user",
    headers={"Authorization": f"Bearer {GITHUB_TOKEN}"}
)

print("Status:", r.status_code)
print("Login:", r.json().get("login"))
print("Message:", r.json().get("message"))

Status: 401
Login: None
Message: Bad credentials